import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

export const dynamic = 'force-dynamic';

export async function POST(req: NextRequest) {
  try {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const formData = await req.formData();
    const file = formData.get("file") as File;

    if (!file) {
      return NextResponse.json({ error: "No audio file provided" }, { status: 400 });
    }

    console.log("[AUDIO API] Received file of size:", file.size, "type:", file.type);

    const arrayBuffer = await file.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);
    const base64Data = buffer.toString("base64");

    const apiKey = process.env.GOOGLE_GENERATIVE_AI_API_KEY;

    if (!apiKey) {
      // Graceful Mock fallback if no API key is provided
      const mockResult = `
        <div style="background: rgba(139, 92, 246, 0.04); border: 1px solid rgba(139, 92, 246, 0.2); border-radius: 8px; padding: 16px; margin: 16px 0; font-family: sans-serif;">
          <div style="display: flex; align-items: center; gap: 8px; margin-bottom: 12px; color: #8b5cf6;">
            <span style="font-size: 18px;">🎙️</span>
            <strong style="font-size: 14px; text-transform: uppercase; letter-spacing: 0.5px;">Cora AI Voice Note Transcription (Mock)</strong>
          </div>
          <p style="font-style: italic; color: #4b5563; font-size: 14.5px; line-height: 1.5; margin: 0 0 12px 0;">
            "We need to finalize the database schema migration by Thursday afternoon. Alex will handle the Postgres vector tables, and Sarah will verify that the Next.js API endpoints are fully authenticated."
          </p>
          <div style="border-top: 1px solid rgba(139, 92, 246, 0.15); padding-top: 12px; margin-top: 12px;">
            <strong style="font-size: 13px; color: #1f2937; display: block; margin-bottom: 6px;">✨ Key Summarized Actions:</strong>
            <ul style="margin: 0; padding-left: 20px; font-size: 13.5px; color: #4b5563;">
              <li>Finalize database schema migration by Thursday afternoon.</li>
              <li>Alex to manage the Postgres vector tables.</li>
              <li>Sarah to verify Next.js API authentication tokens.</li>
            </ul>
          </div>
          <div style="font-size: 11px; color: #9ca3af; margin-top: 12px; font-style: italic;">
            Add GOOGLE_GENERATIVE_AI_API_KEY to your environment for real Gemini multimodal transcription.
          </div>
        </div>
      `;

      return NextResponse.json({ html: mockResult });
    }

    // Call standard Gemini Multimodal API using pure fetch REST
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contents: [
            {
              parts: [
                {
                  inlineData: {
                    mimeType: file.type || "audio/webm",
                    data: base64Data,
                  },
                },
                {
                  text: `Please analyze this audio recording. Perform a precise text transcription first. Following the transcript, provide a high-level summary of the key discussion points and any direct action items. 
                  Return your response strictly as a beautifully structured HTML card with styled elements ready to be inserted directly into a rich-text document. Use a soft purple or indigo borders/background styling in the outer div for a modern premium look. Keep class names inside inline styles. Do not include markdown wraps like \`\`\`html.`,
                },
              ],
            },
          ],
        }),
      }
    );

    if (!response.ok) {
      const errText = await response.text();
      console.error("[Gemini Audio API Error]:", errText);
      throw new Error(`Gemini service failed with status ${response.status}`);
    }

    const resJson = await response.json();
    const resultText = resJson.candidates?.[0]?.content?.parts?.[0]?.text || "Failed to analyze speech.";
    
    // Clean up any potential markdown formatting wraps if generated by Gemini
    const cleanHtml = resultText.replace(/```html/gi, "").replace(/```/g, "").trim();

    return NextResponse.json({ html: cleanHtml });

  } catch (err: any) {
    console.error("Audio API general error:", err);
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
